baseURL = 'https://whlapinel.github.io/python-plc'
languageCode = 'en-us'
title = 'Python PLC Stuff'
copyright = 'Charlotte-Mecklenburg Schools'
theme = 'ananke'
[params]
  custom_css = ["css/custom.css", "css/github-markdown-dark.css"]
